// Unified vendor data entry point.
// The bulk vendor list is auto-generated by scripts/generate-vendors.py from
// data/vendor-seed.json. See lib/vendors.generated.ts.
//
// Types + deterministic-mock helpers live in separate modules so the generated
// file can import them without circular dependencies.

export type { Vendor, VendorReview, VendorCOA } from "./vendors-types";
export { makeReviews, makeCOAs, makeScoreHistory } from "./vendors-helpers";

import type { Vendor } from "./vendors-types";
import { generatedVendors } from "./vendors.generated";

export const vendors: Vendor[] = generatedVendors;

export function getVendor(slug: string): Vendor | undefined {
  return vendors.find((v) => v.slug === slug);
}

/** Vendors that have a real PVS score (top tier). */
export function getScoredVendors(): Vendor[] {
  return vendors.filter((v) => !v.pending);
}

/** Vendors that are seeded but not yet scored — shown with "Pending Verification" badge. */
export function getPendingVendors(): Vendor[] {
  return vendors.filter((v) => v.pending);
}
